spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mp?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    view:
      prefix: /
      suffix: .html
  # 应用名称
  application:
    name: app

# 应用服务 WEB 访问端口
server:
  port: 8080

